---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cilion.cilion.io
  resources:
  - scionpathpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cilion.cilion.io
  resources:
  - scionpathpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - cilion.cilion.io
  resources:
  - scionpathpolicies/status
  verbs:
  - get
  - patch
  - update
