---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cilion.cilion.io
  resources:
  - scionclusterpeers
  - scioncomputedpaths
  - scionpathpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cilion.cilion.io
  resources:
  - scionclusterpeers/finalizers
  - scioncomputedpaths/finalizers
  verbs:
  - update
- apiGroups:
  - cilion.cilion.io
  resources:
  - scionclusterpeers/status
  - scioncomputedpaths/status
  verbs:
  - get
  - patch
  - update
