# This rule is not used by the project cilion itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to cilion.cilion.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cilion
    app.kubernetes.io/managed-by: kustomize
  name: scioncomputedpath-viewer-role
rules:
- apiGroups:
  - cilion.cilion.io
  resources:
  - scioncomputedpaths
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cilion.cilion.io
  resources:
  - scioncomputedpaths/status
  verbs:
  - get
