# This rule is not used by the project cilion itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the cilion.cilion.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cilion
    app.kubernetes.io/managed-by: kustomize
  name: scionpathpolicy-editor-role
rules:
- apiGroups:
  - cilion.cilion.io
  resources:
  - scionpathpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cilion.cilion.io
  resources:
  - scionpathpolicies/status
  verbs:
  - get
